name: spring-app-kt-template
description: Spring + Kotlin
types:
  - app-template
inputs:
  - label: Project name
    type: text
    name: project_name
    global: true
    default: project-name
  
  - label: Group id
    type: text
    name: project_group_id
    global: true
    default: com.stackspot.demo
  
  - label: "Do you want to expose rest api: "
    type: bool
    name: "starter_web"
    default: true

  - label: Image name
    type: text
    name: project_image_name
    global: true

computedInputs: 
  camel_project_name: "{{project_name|to_camel}}"

lifecycle:
  deploy:
    supported-os:
      - windows
      - linux
      - mac
    requirements-check:
      npm:
        check-command: npm --version
        info: npm is not installed
      gradle:
        check-command: ./infra/gradlew -v
        info: gradle is not configured
    deploy-command:
      windows: cmd /c infra\deploy.bat ${stage}
      linux: sh ./infra/deploy.sh ${stage}
      mac: sh ./infra/deploy.sh ${stage}
hooks:
  - type: run
    trigger: after-render
    commands:
    - echo This project deploy command needs a stage parameter(created by your env project), to get some configurations, like namespace, vpc, cluster name.